DROP DATABASE IF EXISTS WORLDINFO;
CREATE DATABASE WORLDINFO;

USE WORLDINFO;

-- PRODUCT TABLE
CREATE TABLE IF NOT EXISTS PRODUCT (
  productid INT AUTO_INCREMENT PRIMARY KEY, 
  name VARCHAR(100)
);

-- PRODUCT RATING TABLE
CREATE TABLE PRODUCTRATING (
  rattingProductId INT AUTO_INCREMENT PRIMARY KEY,
  comment VARCHAR(2000),
  ratting INT
);

-- PRODUCT WITH DETAIL TABLE
CREATE TABLE IF NOT EXISTS PRODUCTWITHDETAIL (
  productDetailId INT AUTO_INCREMENT PRIMARY KEY,    
  price INT,
  productDetail VARCHAR(300),
  name INT,
  ratting INT,
  FOREIGN KEY (name) REFERENCES PRODUCT(productid),
  FOREIGN KEY (ratting) REFERENCES PRODUCTRATING(rattingProductId)
); 

-- INSERT PRODUCT
INSERT INTO PRODUCT(name)  
VALUES ("TFIN BOX");

-- INSERT PRODUCT RATING
INSERT INTO PRODUCTRATING(comment, ratting) 
VALUES ("Very good product in cheap price", 5);

-- INSERT PRODUCT DETAIL
INSERT INTO PRODUCTWITHDETAIL(price, productDetail, name, ratting) 
VALUES (200, 'Made By Syed Abdullah Ali', 1, 1);

SELECT
FULLPRODUCTWITHDETAIL.productDetailId,
FULLPRODUCTWITHDETAIL.productDetail,
FULLPRODUCTWITHDETAIL.price,
PRODUCTRATe.ratting as ratting,
PRODUCTNAME.name as name,
COMMENT.comment as comment
FROM 
PRODUCTWITHDETAIL FULLPRODUCTWITHDETAIL
JOIN 
PRODUCT PRODUCTNAME ON FULLPRODUCTWITHDETAIL.name = PRODUCTNAME.productid
JOIN 
PRODUCTRATING PRODUCTRATe ON FULLPRODUCTWITHDETAIL.ratting = PRODUCTRATe.rattingProductId
JOIN 
PRODUCTRATING PRODUCTCOMMENT ON FULLPRODUCTWITHDETAIL.comment = PRODUCTCOMMENT.rattingProductId;